### PR TITLE
Removing extra body height declaration, adding scroll-behavior: auto …

### PR DESCRIPTION
**Pull request by lukehler**
…for prefers-reduced motion.

### CODE REVIEW

**Comment by lukehler** [comment]
> Issues and pull requests are welcome, but because this is an interview test project, I may not respond and/or merge PRs.

I just wanted to acknowledge that this pull request isn't intended to address a pressing need, but as a demonstration. It was primarily as a quick overview of how to contribute to a project for a mostly non-technical (but interested!) audience. Thanks for sharing this and TIL about the `list-style`s

**Comment by mike-engel** [comment]
@lukehler That was actually copy/pasted from another project, so I need to update that. Good catch!

**Comment by mike-engel** [comment]
@all-contributors please add @lukehler for code

**Comment by mike-engel** [comment]
@lukehler This is now available with version 1.1.0. Thanks again!

**Pull request merged**
